#!/usr/bin/env python3
"""Regenerate the agent-guard digest policy for safety-critical demo files."""

from __future__ import annotations

import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POLICY_PATH = ROOT / ".agent-guard" / "digest-policy.yaml"
PINNED_FILES = [
    ("readme", "README.md"),
    ("policy_wrapper", "scripts/policy_admit.py"),
    ("policy_matrix", ".agent-policy/policy.toml"),
]


def sha256_hex(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    lines = [
        "# Generated by scripts/update_digests.py.",
        "checks:",
    ]
    for check_id, rel_path in PINNED_FILES:
        digest = sha256_hex(ROOT / rel_path)
        lines.extend(
            [
                f"  - id: {check_id}",
                f"    path: {rel_path}",
                f"    sha256: {digest}",
            ]
        )
    POLICY_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"updated {POLICY_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
